apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-state
  namespace: verentis-apps
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
